###
POST http://localhost:8080/api/suggestion
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIke0pXVC5JU1NVRVIiLCJ1c2VyX2lkeCI6MX0.8hjiKaoR016zU1u9z7JygRpcoMufVtj6UCs3uEarYl4

{
  "content": "도담이에게 건의하니당"
}

###